name: publish
on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Query releases for cli
      run: |
         CLI_TAG="$(curl --silent "https://api.github.com/repos/vmware-tanzu/carvel-ytt/releases/latest" | grep '"tag_name":' |  sed -E 's/.*"([^"]+)".*/\1/')"

         echo "CLI is @ ${CLI_TAG}"
      shell: bash
  deploy:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run test --if-present
      - run: npm run build  --if-present
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.GH_ACTION_NPM_TOKEN }}